[package]
name = "volnita"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termcolor = "1.1.3"
git2 = "0.17.1"
tui = "0.19.0"
tui-input = "0.7.0"
crossterm = "0.26.1"
serde = "1.0.163"
