[package]
name = "volnita"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termcolor = "1.1.3"
git2 = "0.15.0"
tui = "0.19.0"
tui-input = "0.6.1"
crossterm = "0.25.0"